filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/app.json
    json.keys_under_root: true
    json.overwrite_keys: true

output.logstash:
  hosts: ["logstash:5044"]